sudo: required
dist: trusty
language: cpp

matrix:
  include:
    # - compiler: clang
    #   addons:
    #     apt:
    #       packages:
    #         - uuid-dev
    #   env:
    #     - COMPILER=3.8 LLVM_VERSION=3.8.0 BUILD_TYPE=Debug
    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - uuid-dev
    #   env:
    #     - COMPILER=3.8 LLVM_VERSION=3.8.0 BUILD_TYPE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - uuid-dev
      env:
        - COMPILER=4.0 LLVM_VERSION=4.0.0 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - uuid-dev
      env:
        - COMPILER=4.0 LLVM_VERSION=4.0.0 BUILD_TYPE=Release
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #         - uuid-dev
    #   env:
    #     - COMPILER=6 BUILD_TYPE=Debug
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #         - uuid-dev
    #   env:
    #     - COMPILER=6 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - uuid-dev
      env:
        - COMPILER=7 BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - uuid-dev
      env:
        - COMPILER=7 BUILD_TYPE=Release
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Debug
      osx_image: xcode9
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Release
      osx_image: xcode9

before_install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}/local
  - cd ${DEPS_DIR}
  - export CXXFLAGS="-isystem ${DEPS_DIR}/local/include"
  - export PKG_CONFIG_PATH=${DEPS_DIR}/local/lib/pkgconfig
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/local/lib"
  - export LDFLAGS="-L${DEPS_DIR}/local/lib"

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  ############################################################################
  # Install clang on linux
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX}" == "clang++" ]]; then
      travis_retry wget --quiet -O - http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz | tar --strip-components=1 ${TAR_FLAGS} -xJ -C ${DEPS_DIR}/local

      export PATH=${DEPS_DIR}/local/bin:${PATH}
      export LDFLAGS="${LDFLAGS} -lc++ -lc++abi -lm"
      export CXXFLAGS="${CXXFLAGS} -isystem ${DEPS_DIR}/local/include/c++/v1 -stdlib=libc++"
      export CXX="clang-${COMPILER}" CC="clang-${COMPILER}"
      ${CXX} -v
    fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${COMPILER}" CC="gcc-${COMPILER}"; fi

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      wget http://downloads.sourceforge.net/project/boost/boost/1.64.0/boost_1_64_0.tar.bz2 TIMEOUT 6000
      tar xf boost_1_64_0.tar.bz2
      echo "Build boost using ${CXX}"
      if [[ "${CXX}" == "clang-${COMPILER}" ]]; then
        cd boost_1_64_0 && echo "using clang : ${COMPILER} : clang-${COMPILER} : <cxxflags>\"-std=c++14 ${CXXFLAGS}\" ;" > user-config.jam && ./bootstrap.sh && ./b2 address-model=64 toolset=clang architecture=x86 variant=release link=static threading=multi --with-system --prefix=${DEPS_DIR}/local --user-config=./user-config.jam install 1> /dev/null
      else
        cd boost_1_64_0 && echo "using gcc : ${COMPILER} : g++-${COMPILER} : <cxxflags>\"-std=c++14\" ;" > user-config.jam &&  ./bootstrap.sh && ./b2 address-model=64 toolset=gcc architecture=x86 variant=release link=static threading=multi --with-system --prefix=${DEPS_DIR}/local --user-config=./user-config.jam install 1> /dev/null
      fi
      cd ..
    fi

  - |
    git clone --single-branch https://github.com/boostorg/beast.git
    cp -r ./beast/include/boost ${DEPS_DIR}/local/include/

  - |
    git clone --single-branch https://github.com/fmtlib/fmt.git --branch 4.0.0
    cd fmt
    cmake -DFMT_DOC=OFF -DFMT_TEST=OFF -DFMT_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/local
    make install

  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - git clone -b develop --single-branch --recursive https://github.com/dirkvdb/utils.git ../utils

script:
  - git submodule update --init --recursive
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=${DEPS_DIR}/local -DSTANDALONE=ON .
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_failure:
  - cat Testing/Temporary/LastTest.log
